ARG HOST_CONTAINER
ARG TARGET_CONTAINER
FROM ${HOST_CONTAINER} as host
ARG TARGET_ARCH

ADD hello.c .

RUN clang -fuse-ld=lld -target ${TARGET_ARCH}-redhat-linux --sysroot=/usr/${TARGET_ARCH}-redhat-linux/ hello.c

ARG TARGET_CONTAINER
FROM ${TARGET_CONTAINER}
COPY --from=host  /a.out /
RUN ./a.out
